name: Multi-Tier CI Pipeline

on:
  push:
    branches: [ master, main ]

jobs:
  test-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar codigo
        uses: actions/checkout@v4

      - name: 2. Levantar con Docker Compose
        run: |
          docker compose up -d --build
          echo "Esperando a que los servicios se estabilicen..."
          sleep 30

      - name: 3. Debug - Ver estado de contenedores
        run: docker compose ps

      - name: 4. Test Frontend
        run: curl -v http://localhost:8080 | grep "200 OK"

      - name: 5. Test Backend
        run: curl -s http://localhost:5000/datos | grep "online"

      - name: 6. Ver logs si algo fallo
        if: failure()
        run: docker compose logs
